require('./basic.js');
require('./getter.js');
require('./mvc.js');
require('./on.js');
require('./once.js');
require('./function.js');
require('./when.js');
require('./forEach.js');
require('./destroy.js');
